import pandas as pd

# Ask for the input and output file names
input_file = input("Enter the path to the input CSV file: ")
output_file = input("Enter the path for the output CSV file: ")

# Country codes mapping
country_codes = {
	"Andorra": "AD",
	"United Arab Emirates": "AE",
	"Afghanistan": "AF",
	"Antigua and Barbuda": "AG",
	"Anguilla": "AI",
	"Albania": "AL",
	"Armenia": "AM",
	"Netherlands Antilles": "AN",
	"Angola": "AO",
	"Antarctica": "AQ",
	"Argentina": "AR",
	"American Samoa": "AS",
	"Austria": "AT",
	"Australia": "AU",
	"Aruba": "AW",
	"Azerbaijan": "AZ",
	"Bosnia and Herzegovina": "BA",
	"Barbados": "BB",
	"Bangladesh": "BD",
	"Belgium": "BE",
	"Burkina Faso": "BF",
	"Bulgaria": "BG",
	"Bahrain": "BH",
	"Burundi": "BI",
	"Benin": "BJ",
	"Bermuda": "BM",
	"Brunei": "BN",
	"Bolivia": "BO",
	"Brazil": "BR",
	"Bahamas": "BS",
	"Bhutan": "BT",
	"Bouvet Island": "BV",
	"Botswana": "BW",
	"Belarus": "BY",
	"Belize": "BZ",
	"Canada": "CA",
	"Cocos (Keeling) Islands": "CC",
	"Congo, Democratic Republic of the": "CD",
	"Central African Republic": "CF",
	"Congo, Republic of the": "CG",
	"Switzerland": "CH",
	"Côte d’Ivoire": "CI",
	"Cook Islands": "CK",
	"Chile": "CL",
	"Cameroon": "CM",
	"China mainland": "CN",
	"Colombia": "CO",
	"Costa Rica": "CR",
	"Serbia & Montenegro": "CS",
	"Cuba": "CU",
	"Cape Verde": "CV",
	"Christmas Island": "CX",
	"Cyprus": "CY",
	"Czech Republic": "CZ",
	"Germany": "DE",
	"Djibouti": "DJ",
	"Denmark": "DK",
	"Dominica": "DM",
	"Dominican Republic": "DO",
	"Algeria": "DZ",
	"Ecuador": "EC",
	"Estonia": "EE",
	"Egypt": "EG",
	"Western Sahara": "EH",
	"Eritrea": "ER",
	"Spain": "ES",
	"Ethiopia": "ET",
	"Finland": "FI",
	"Fiji": "FJ",
	"Falkland Islands": "FK",
	"Micronesia": "FM",
	"Faroe Islands": "FO",
	"France": "FR",
	"Gabon": "GA",
	"Grenada": "GD",
	"Georgia": "GE",
	"French Guiana": "GF",
	"Ghana": "GH",
	"Gibraltar": "GI",
	"Greenland": "GL",
	"Gambia": "GM",
	"Guinea": "GN",
	"Guadeloupe": "GP",
	"Equatorial Guinea": "GQ",
	"Greece": "GR",
	"South Georgia and the South Sandwich Islands": "GS",
	"Guatemala": "GT",
	"Guam": "GU",
	"Guinea-Bissau": "GW",
	"Guyana": "GY",
	"Hong Kong": "HK",
	"Heard Island and Mcdonald Islands": "HM",
	"Honduras": "HN",
	"Croatia": "HR",
	"Haiti": "HT",
	"Hungary": "HU",
	"Indonesia": "ID",
	"Ireland": "IE",
	"Israel": "IL",
	"India": "IN",
	"British Indian Ocean Territory": "IO",
	"Iraq": "IQ",
	"Iran, Islamic Republic of": "IR",
	"Iceland": "IS",
	"Italy": "IT",
	"Jamaica": "JM",
	"Jordan": "JO",
	"Japan": "JP",
	"Kenya": "KE",
	"Kyrgyzstan": "KG",
	"Cambodia": "KH",
	"Kiribati": "KI",
	"Comoros": "KM",
	"St. Kitts and Nevis": "KN",
	"Korea, Democratic People’s Republic of": "KP",
	"Korea, Republic of": "KR",
	"Kuwait": "KW",
	"Cayman Islands": "KY",
	"Kazakhstan": "KZ",
	"Laos": "LA",
	"Lebanon": "LB",
	"St. Lucia": "LC",
	"Liechtenstein": "LI",
	"Sri Lanka": "LK",
	"Liberia": "LR",
	"Lesotho": "LS",
	"Lithuania": "LT",
	"Luxembourg": "LU",
	"Latvia": "LV",
	"Libya": "LY",
	"Morocco": "MA",
	"Monaco": "MC",
	"Moldova": "MD",
	"Madagascar": "MG",
	"Marshall Islands": "MH",
	"North Macedonia": "MK",
	"Mali": "ML",
	"Myanmar": "MM",
	"Mongolia": "MN",
	"Macau": "MO",
	"Northern Mariana Islands": "MP",
	"Martinique": "MQ",
	"Mauritania": "MR",
	"Montserrat": "MS",
	"Malta": "MT",
	"Mauritius": "MU",
	"Maldives": "MV",
	"Malawi": "MW",
	"Mexico": "MX",
	"Malaysia": "MY",
	"Mozambique": "MZ",
	"Namibia": "NA",
	"New Caledonia": "NC",
	"Niger": "NE",
	"Norfolk Island": "NF",
	"Nigeria": "NG",
	"Nicaragua": "NI",
	"Netherlands": "NL",
	"Norway": "NO",
	"Nepal": "NP",
	"Nauru": "NR",
	"Niue": "NU",
	"New Zealand": "NZ",
	"Oman": "OM",
	"Panama": "PA",
	"Peru": "PE",
	"French Polynesia": "PF",
	"Papua New Guinea": "PG",
	"Philippines": "PH",
	"Pakistan": "PK",
	"Poland": "PL",
	"Saint Pierre & Miquelon": "PM",
	"Pitcairn": "PN",
	"Puerto Rico": "PR",
	"Palestinian Territory, Occupied": "PS",
	"Portugal": "PT",
	"Palau": "PW",
	"Paraguay": "PY",
	"Qatar": "QA",
	"Réunion": "RE",
	"Romania": "RO",
	"Russia": "RU",
	"Rwanda": "RW",
	"Saudi Arabia": "SA",
	"Solomon Islands": "SB",
	"Seychelles": "SC",
	"Sudan": "SD",
	"Sweden": "SE",
	"Singapore": "SG",
	"Saint Helena": "SH",
	"Slovenia": "SI",
	"Svalbard & Jan Mayen": "SJ",
	"Slovakia": "SK",
	"Sierra Leone": "SL",
	"San Marino": "SM",
	"Senegal": "SN",
	"Somalia": "SO",
	"Suriname": "SR",
	"São Tomé and Príncipe": "ST",
	"El Salvador": "SV",
	"Syrian Arab Republic": "SY",
	"Eswatini": "SZ",
	"Turks and Caicos Islands": "TC",
	"Chad": "TD",
	"French Southern Territories": "TF",
	"Togo": "TG",
	"Thailand": "TH",
	"Tajikistan": "TJ",
	"Tokelau": "TK",
	"Timor-Leste": "TL",
	"Turkmenistan": "TM",
	"Tunisia": "TN",
	"Tonga": "TO",
	"Türkiye": "TR",
	"Trinidad and Tobago": "TT",
	"Tuvalu": "TV",
	"Taiwan": "TW",
	"Tanzania": "TZ",
	"Ukraine": "UA",
	"Uganda": "UG",
	"United Kingdom": "UK",
	"United States Minor Outlying Islands": "UM",
	"United States": "US",
	"Uruguay": "UY",
	"Uzbekistan": "UZ",
	"Holy See (Vatican City State)": "VA",
	"St. Vincent and the Grenadines": "VC",
	"Venezuela": "VE",
	"British Virgin Islands": "VG",
	"Virgin Islands, U.S.": "VI",
	"Vietnam": "VN",
	"Vanuatu": "VU",
	"Wallis and Futuna": "WF",
	"Samoa": "WS",
	"Yemen": "YE",
	"Mayotte": "YT",
	"South Africa": "ZA",
	"Zambia": "ZM",
	"Zimbabwe": "ZW",
	"Åland Islands": "AX",
	"Saint Barthélemy": "BL",
	"Sint Eustatius and Saba": "BQ",
	"Curaçao": "CW",
	"United Kingdom": "GB",
	"Guernsey": "GG",
	"Isle of Man": "IM",
	"Jersey": "JE",
	"Montenegro": "ME",
	"Saint Martin (French part)": "MF",
	"Serbia": "RS",
	"South Sudan": "SS",
	"Sint Maarten (Dutch part)": "SX",
	"Kosovo": "XK",
	"Unknown": "ZZ",
	"Eswatini": "ZZ",
	    # Add the rest of the mappings here...
}

# Reading the CSV data from the input file
df = pd.read_csv(input_file)

# Melting the dataframe to transform it
df_melted = df.melt(id_vars=["Date"], var_name="Country", value_name="Daily Device Installs")

# Function to map full country names to their codes
def map_country_codes(country):
    if country in country_codes:
        return country_codes[country]
    return country

# Applying the mapping function
df_melted["Country"] = df_melted["Country"].apply(map_country_codes)

# Optionally, you might want to sort by Date or Country for better readability
df_melted.sort_values(by=["Date", "Country"], inplace=True)

# Output the result to the specified output file
df_melted.to_csv(output_file, index=False)

print(f"Data successfully transformed and saved to {output_file}")
